### PR TITLE
FIX: SS_Report canView should check permissions

### LINKED ISSUE #13: SS_Report::canView() always returns true
see https://github.com/silverstripe-labs/silverstripe-reports/blob/3/code/Report.php#L303-L313

### PR DESCRIPTION
**Pull request by christopherdarling**
... checks for ADMIN / CMS_ACCESS_ReportAdmin (from ReportAdmin)

fixes #13

### CODE REVIEW

**Comment by dhensby** [comment]
You don't need to check the ADMIN permission AND another... ADMIN will inherit all permissions (or if it doesn't, it's by intention by the site dev)

**Comment by christopherdarling** [comment]
ahh right, I had based it on SiteTree::canView() - https://github.com/silverstripe/silverstripe-cms/blob/3/code/model/SiteTree.php#L905 do you want me to update this PR and do one for SiteTree also?

**Comment by tractorcow** [comment]
Don't forget `CMS_ACCESS_LeftAndMain` for `any cms section` access.

**Comment by tractorcow** [comment]
SiteTree::canView() is also terribad. :P

**Comment by tractorcow** [comment]
Can you change this line

https://github.com/silverstripe-labs/silverstripe-reports/blob/3/.travis.yml#L16

to 

`      env: DB=MYSQL CORE_RELEASE=3`

To fix tests

**Comment by kinglozzer** [comment]
Do we need to add an extension hook too? :)

**Comment by tractorcow** [comment]
It would be a good idea ,if you want to add an extendedCan just before your addition. :)

**Comment by christopherdarling** [comment]
I've added 'CMS_ACCESS_LeftAndMain' to the permission checks, done the travis update and added an extension hook.

While doing the extension hook I noticed that a lot of places don't seem to follow the same pattern, some extension hooks are done before the Permission::check() and others afterwards. I imagine these should probably be consistent in behavior?  Having the hook before the before the permission check seems to make the most sense to me.  Happy to go through and update ones I can spot just let me know what branch I should PR against :-)

The travis builds failed on PHP 5.3 MYSQL and PHP 5.3 PGSQL, do these lines https://github.com/silverstripe-labs/silverstripe-reports/blob/3/.travis.yml#L10-L11 need updating to CORE_RELEASE=3 also?

**Comment by tractorcow** [comment]
The way that you've implemented it is fine... good job. :D

Sorry, I think you're right, you'll need to fix all of the MASTER references in .travis.yml to 3

**Comment by tractorcow** [comment]
@dhensby fixed the tests in https://github.com/silverstripe-labs/silverstripe-reports/pull/22

just rebase and we can close this. :)

**Comment by christopherdarling** [comment]
rebased :-)

**Comment by dhensby** [comment]
Can I be a complete pain and ask for these to be squashed? Sorry - they are just two commits where the second basically overwrites the first, so it's a bit polluting to have them both.

If you do this:

```sh
$ git checkout patch-2
$ git reset HEAD^
$ git add .
$ git commit --amend --no-edit
$ git push -f origin patch-2
```

Then that'll do the job!

**Comment by christopherdarling** [comment]
sure, done :-)

**Comment by tractorcow** [comment]
Thanks @christopherdarling

**Comment by tractorcow** [comment]
Apparently this feature broke the CMS. https://github.com/silverstripe-labs/silverstripe-reports/issues/24

You did test this right?

**Comment by christopherdarling** [comment]
my apologies @tractorcow the original PR was tested but I didn't test the addition of the extension hook, I wrongly assumed extendedCan() came from Object. Sorry!

**Pull request merged**
